
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "touch/src",
  "Ext.device.Purchases.Product": "touch/src/device/purchases/Sencha.js",
  "Ext.device.filesystem.DirectoryEntry": "touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.Entry": "touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.FileEntry": "touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.FileSystem": "touch/src/device/filesystem/HTML5.js",
  "Ext.device.purchases.Purchase": "touch/src/device/purchases/Sencha.js",
  "Ext.device.sqlite.Database": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSet": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSetRowList": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLTransaction": "touch/src/device/sqlite/Sencha.js",
  "RM": "app",
  "TouchCalendarViewModel": "app/component/touchcalendar/TouchCalendarView.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.ActionSheet": [],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.AnimationQueue": [],
  "Ext.Audio": [],
  "Ext.BingMap": [],
  "Ext.Button": [],
  "Ext.Component": [
    "Ext.lib.Component"
  ],
  "Ext.ComponentManager": [
    "Ext.ComponentMgr"
  ],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "Ext.lib.Container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [
    "Ext.EventedBase"
  ],
  "Ext.Img": [],
  "Ext.ItemCollection": [],
  "Ext.Label": [],
  "Ext.LoadMask": [],
  "Ext.Map": [],
  "Ext.Mask": [],
  "Ext.Media": [],
  "Ext.Menu": [],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "Ext.lib.Panel"
  ],
  "Ext.ProgressIndicator": [],
  "Ext.Promise": [],
  "Ext.SegmentedButton": [],
  "Ext.Sheet": [],
  "Ext.Sortable": [],
  "Ext.Spacer": [],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [],
  "Ext.TitleBar": [],
  "Ext.Toolbar": [],
  "Ext.Video": [],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "Ext.Carousel"
  ],
  "Ext.carousel.Indicator": [
    "Ext.Carousel.Indicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.data.ArrayStore": [],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [],
  "Ext.data.JsonP": [
    "Ext.util.JSONP"
  ],
  "Ext.data.JsonStore": [],
  "Ext.data.Model": [
    "Ext.data.Record"
  ],
  "Ext.data.ModelManager": [
    "Ext.ModelMgr",
    "Ext.ModelManager"
  ],
  "Ext.data.NodeInterface": [
    "Ext.data.Node"
  ],
  "Ext.data.NodeStore": [],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [],
  "Ext.data.StoreManager": [
    "Ext.StoreMgr",
    "Ext.data.StoreMgr",
    "Ext.StoreManager"
  ],
  "Ext.data.TreeStore": [],
  "Ext.data.Types": [],
  "Ext.data.Validations": [
    "Ext.data.validations"
  ],
  "Ext.data.association.Association": [
    "Ext.data.Association"
  ],
  "Ext.data.association.BelongsTo": [
    "Ext.data.BelongsToAssociation"
  ],
  "Ext.data.association.HasMany": [
    "Ext.data.HasManyAssociation"
  ],
  "Ext.data.association.HasOne": [
    "Ext.data.HasOneAssociation"
  ],
  "Ext.data.identifier.Sequential": [],
  "Ext.data.identifier.Simple": [],
  "Ext.data.identifier.Uuid": [],
  "Ext.data.plugin.Buffered": [],
  "Ext.data.proxy.Ajax": [
    "Ext.data.HttpProxy",
    "Ext.data.AjaxProxy"
  ],
  "Ext.data.proxy.Client": [
    "Ext.proxy.ClientProxy"
  ],
  "Ext.data.proxy.Direct": [
    "Ext.data.DirectProxy"
  ],
  "Ext.data.proxy.JsonP": [
    "Ext.data.ScriptTagProxy"
  ],
  "Ext.data.proxy.LocalStorage": [
    "Ext.data.LocalStorageProxy"
  ],
  "Ext.data.proxy.Memory": [
    "Ext.data.MemoryProxy"
  ],
  "Ext.data.proxy.Proxy": [
    "Ext.data.DataProxy",
    "Ext.data.Proxy"
  ],
  "Ext.data.proxy.Rest": [
    "Ext.data.RestProxy"
  ],
  "Ext.data.proxy.Server": [
    "Ext.data.ServerProxy"
  ],
  "Ext.data.proxy.SessionStorage": [
    "Ext.data.SessionStorageProxy"
  ],
  "Ext.data.proxy.Sql": [
    "Ext.data.proxy.SQL"
  ],
  "Ext.data.proxy.WebStorage": [
    "Ext.data.WebStorageProxy"
  ],
  "Ext.data.reader.Array": [
    "Ext.data.ArrayReader"
  ],
  "Ext.data.reader.Json": [
    "Ext.data.JsonReader"
  ],
  "Ext.data.reader.Reader": [
    "Ext.data.Reader",
    "Ext.data.DataReader"
  ],
  "Ext.data.reader.Xml": [
    "Ext.data.XmlReader"
  ],
  "Ext.data.writer.Json": [
    "Ext.data.JsonWriter"
  ],
  "Ext.data.writer.Writer": [
    "Ext.data.DataWriter",
    "Ext.data.Writer"
  ],
  "Ext.data.writer.Xml": [
    "Ext.data.XmlWriter"
  ],
  "Ext.dataview.DataView": [
    "Ext.DataView"
  ],
  "Ext.dataview.IndexBar": [
    "Ext.IndexBar"
  ],
  "Ext.dataview.List": [
    "Ext.List"
  ],
  "Ext.dataview.ListItemHeader": [],
  "Ext.dataview.NestedList": [
    "Ext.NestedList"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [],
  "Ext.dataview.component.ListItem": [],
  "Ext.dataview.component.SimpleListItem": [],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Accelerometer": [],
  "Ext.device.Browser": [],
  "Ext.device.Camera": [],
  "Ext.device.Capture": [],
  "Ext.device.Communicator": [],
  "Ext.device.Compass": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.FileSystem": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Globalization": [],
  "Ext.device.Media": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Push": [],
  "Ext.device.SQLite": [],
  "Ext.device.Splashscreen": [],
  "Ext.device.Storage": [],
  "Ext.device.Tunnel": [],
  "Ext.device.accelerometer.Abstract": [],
  "Ext.device.accelerometer.Cordova": [
    "Ext.device.accelerometer.PhoneGap"
  ],
  "Ext.device.accelerometer.Simulator": [],
  "Ext.device.browser.Abstract": [],
  "Ext.device.browser.Cordova": [],
  "Ext.device.browser.Simulator": [],
  "Ext.device.browser.Window": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.Cordova": [
    "Ext.device.camera.PhoneGap"
  ],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.capture.Abstract": [
    "Ext.device.capture.Simulator"
  ],
  "Ext.device.capture.Cordova": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.compass.Abstract": [],
  "Ext.device.compass.Cordova": [
    "Ext.device.compass.PhoneGap"
  ],
  "Ext.device.compass.Simulator": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.Cordova": [
    "Ext.device.connection.PhoneGap"
  ],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Cordova": [
    "Ext.device.contacts.PhoneGap"
  ],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.Cordova": [
    "Ext.device.device.PhoneGap"
  ],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.filesystem.Abstract": [],
  "Ext.device.filesystem.Chrome": [],
  "Ext.device.filesystem.Cordova": [
    "Ext.device.filesystem.PhoneGap"
  ],
  "Ext.device.filesystem.DirectoryEntry": [],
  "Ext.device.filesystem.Entry": [],
  "Ext.device.filesystem.FileEntry": [],
  "Ext.device.filesystem.FileSystem": [],
  "Ext.device.filesystem.HTML5": [],
  "Ext.device.filesystem.Sencha": [],
  "Ext.device.filesystem.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Cordova": [
    "Ext.device.geolocation.PhoneGap"
  ],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.globalization.Abstract": [],
  "Ext.device.globalization.Cordova": [
    "Ext.device.globalization.PhoneGap"
  ],
  "Ext.device.globalization.Simulator": [],
  "Ext.device.media.Abstract": [],
  "Ext.device.media.Cordova": [
    "Ext.device.media.PhoneGap"
  ],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.Cordova": [
    "Ext.device.notification.PhoneGap"
  ],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Purchase": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Cordova": [],
  "Ext.device.push.Sencha": [],
  "Ext.device.splashscreen.Abstract": [],
  "Ext.device.splashscreen.Cordova": [
    "Ext.device.splashscreen.PhoneGap"
  ],
  "Ext.device.splashscreen.Simulator": [],
  "Ext.device.sqlite.Database": [],
  "Ext.device.sqlite.SQLResultSet": [],
  "Ext.device.sqlite.SQLResultSetRowList": [],
  "Ext.device.sqlite.SQLTransaction": [],
  "Ext.device.sqlite.Sencha": [],
  "Ext.device.storage.Abstract": [],
  "Ext.device.storage.Cordova": [
    "Ext.device.storage.PhoneGap"
  ],
  "Ext.device.storage.HTML5.Database": [],
  "Ext.device.storage.HTML5.HTML5": [],
  "Ext.device.storage.HTML5.SQLStatement": [],
  "Ext.device.storage.Simulator": [],
  "Ext.device.tunnel.Abstract": [],
  "Ext.device.tunnel.Connection": [],
  "Ext.device.tunnel.Sencha": [],
  "Ext.device.tunnel.Simulator": [],
  "Ext.direct.Event": [],
  "Ext.direct.ExceptionEvent": [],
  "Ext.direct.JsonProvider": [],
  "Ext.direct.Manager": [
    "Ext.Direct"
  ],
  "Ext.direct.PollingProvider": [],
  "Ext.direct.Provider": [],
  "Ext.direct.RemotingEvent": [],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [],
  "Ext.direct.Transaction": [
    "Ext.Direct.Transaction"
  ],
  "Ext.dom.CompositeElement": [
    "Ext.CompositeElement"
  ],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [
    "Ext.EventObject"
  ],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.EdgeSwipe": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "Ext.form.Checkbox"
  ],
  "Ext.field.DatePicker": [
    "Ext.form.DatePicker"
  ],
  "Ext.field.DatePickerNative": [
    "Ext.form.DatePickerNative"
  ],
  "Ext.field.Email": [
    "Ext.form.Email"
  ],
  "Ext.field.Field": [
    "Ext.form.Field"
  ],
  "Ext.field.File": [],
  "Ext.field.FileInput": [],
  "Ext.field.Hidden": [
    "Ext.form.Hidden"
  ],
  "Ext.field.Input": [],
  "Ext.field.Number": [
    "Ext.form.Number"
  ],
  "Ext.field.Password": [
    "Ext.form.Password"
  ],
  "Ext.field.Radio": [
    "Ext.form.Radio"
  ],
  "Ext.field.Search": [
    "Ext.form.Search"
  ],
  "Ext.field.Select": [
    "Ext.form.Select"
  ],
  "Ext.field.Slider": [
    "Ext.form.Slider"
  ],
  "Ext.field.Spinner": [
    "Ext.form.Spinner"
  ],
  "Ext.field.Text": [
    "Ext.form.Text"
  ],
  "Ext.field.TextArea": [
    "Ext.form.TextArea"
  ],
  "Ext.field.TextAreaInput": [],
  "Ext.field.Toggle": [
    "Ext.form.Toggle"
  ],
  "Ext.field.Url": [
    "Ext.form.Url"
  ],
  "Ext.form.FieldSet": [],
  "Ext.form.Panel": [
    "Ext.form.FormPanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [],
  "Ext.fx.animation.Fade": [
    "Ext.fx.animation.FadeIn"
  ],
  "Ext.fx.animation.FadeOut": [],
  "Ext.fx.animation.Flip": [],
  "Ext.fx.animation.Pop": [
    "Ext.fx.animation.PopIn"
  ],
  "Ext.fx.animation.PopOut": [],
  "Ext.fx.animation.Slide": [
    "Ext.fx.animation.SlideIn"
  ],
  "Ext.fx.animation.SlideOut": [],
  "Ext.fx.animation.Wipe": [
    "Ext.fx.animation.WipeIn"
  ],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [],
  "Ext.fx.easing.EaseOut": [],
  "Ext.fx.easing.Linear": [],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [],
  "Ext.fx.layout.card.Cube": [],
  "Ext.fx.layout.card.Fade": [],
  "Ext.fx.layout.card.Flip": [],
  "Ext.fx.layout.card.Pop": [],
  "Ext.fx.layout.card.Reveal": [],
  "Ext.fx.layout.card.Scroll": [],
  "Ext.fx.layout.card.ScrollCover": [],
  "Ext.fx.layout.card.ScrollReveal": [],
  "Ext.fx.layout.card.Slide": [],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [],
  "Ext.layout.Card": [],
  "Ext.layout.Default": [],
  "Ext.layout.Fit": [],
  "Ext.layout.FlexBox": [],
  "Ext.layout.Float": [],
  "Ext.layout.HBox": [],
  "Ext.layout.VBox": [],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [
    "Ext.util.Observable"
  ],
  "Ext.mixin.Progressable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "Ext.NavigationView"
  ],
  "Ext.picker.Date": [
    "Ext.DatePicker"
  ],
  "Ext.picker.Picker": [
    "Ext.Picker"
  ],
  "Ext.picker.Slot": [
    "Ext.Picker.Slot"
  ],
  "Ext.plugin.BufferedList": [],
  "Ext.plugin.ListPaging": [],
  "Ext.plugin.PullRefresh": [],
  "Ext.plugin.SortableList": [],
  "Ext.scroll.Indicator": [
    "Ext.util.Indicator"
  ],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [
    "Ext.util.ScrollView"
  ],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Rounded": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.slider.Slider": [],
  "Ext.slider.Thumb": [],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "Ext.TabBar"
  ],
  "Ext.tab.Panel": [
    "Ext.TabPanel"
  ],
  "Ext.tab.Tab": [
    "Ext.Tab"
  ],
  "Ext.table.Cell": [],
  "Ext.table.Row": [],
  "Ext.table.Table": [],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Audio": [],
  "Ext.util.BufferedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [
    "Ext.util.GeoLocation"
  ],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.InputBlocker": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.ActionOverFlowMenuButton": [],
  "Ext.ux.ApplicationMenu": [],
  "Ext.ux.ContextMenu": [],
  "Ext.ux.MenuButton": [],
  "Ext.ux.TabMenuButton": [],
  "Ext.ux.device.Analytics": [],
  "Ext.ux.device.Twitter": [],
  "Ext.ux.device.analytics.Abstract": [],
  "Ext.ux.device.analytics.Cordova": [],
  "Ext.ux.device.twitter.Abstract": [],
  "Ext.ux.device.twitter.Cordova": [],
  "Ext.ux.parse.Helper": [
    "ParseHelper"
  ],
  "Ext.ux.parse.Model": [],
  "Ext.ux.parse.Proxy": [],
  "Ext.ux.parse.Reader": [],
  "Ext.ux.parse.Store": [],
  "Ext.ux.parse.association.Pointer": [],
  "Ext.ux.parse.association.Relation": [],
  "Ext.viewport.Android": [],
  "Ext.viewport.Default": [],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Ext.viewport.WindowsPhone": [
    "Ext.viewport.WP"
  ],
  "RM.component.CalcKeypad": [],
  "RM.component.ChooseInvoiceDiscount": [],
  "RM.component.ChooseInvoiceItem": [],
  "RM.component.CustInvSummaryList": [],
  "RM.component.DataEntryKeypad": [],
  "RM.component.DropdownButton": [],
  "RM.component.DropdownMenu": [],
  "RM.component.DropdownOverlay": [],
  "RM.component.DurationField": [],
  "RM.component.DurationPicker": [],
  "RM.component.ExtDatePickerField": [],
  "RM.component.ExtEmailField": [],
  "RM.component.ExtNumberField": [],
  "RM.component.ExtSelectField": [],
  "RM.component.ExtTextField": [],
  "RM.component.InvoiceLineItems": [],
  "RM.component.InvoiceTimeSelectDetailPan": [],
  "RM.component.InvoicesList": [],
  "RM.component.PayAmountInputCalc": [],
  "RM.component.PinKeypad": [],
  "RM.component.PinOptions": [],
  "RM.component.Popup": [],
  "RM.component.PopupNotes": [],
  "RM.component.RMAmountField": [],
  "RM.component.RMAmountFieldKeyPad": [],
  "RM.component.RMCanvas": [],
  "RM.component.RMCheckbox": [],
  "RM.component.RMComponent": [],
  "RM.component.RMList": [],
  "RM.component.RMMsgPopup": [],
  "RM.component.RMNumberField": [],
  "RM.component.RMPhoneField": [],
  "RM.component.RMPicker": [],
  "RM.component.RMPullRefresh": [],
  "RM.component.RMSelectScreenField": [],
  "RM.component.RMToggleField": [],
  "RM.component.SecureButton": [],
  "RM.component.SecureFormPanel": [],
  "RM.component.SecurePanel": [],
  "RM.component.SortSearchBar": [],
  "RM.component.VisibleOnFocus": [],
  "RM.component.slidenavigation.View": [],
  "RM.component.touchcalendar.TouchCalendarSimpleEvents": [],
  "RM.component.touchcalendar.TouchCalendarView": [],
  "RM.controller.AboutC": [],
  "RM.controller.AcceptPaymentC": [],
  "RM.controller.AccountsC": [],
  "RM.controller.AddNoteC": [],
  "RM.controller.AppStopC": [],
  "RM.controller.BillsC": [],
  "RM.controller.BudgetLineItemsC": [],
  "RM.controller.CashBooksC": [],
  "RM.controller.ContactDetailC": [],
  "RM.controller.ContactsC": [],
  "RM.controller.CoreSettingsC": [],
  "RM.controller.CreateItemC": [],
  "RM.controller.CreatePinC": [],
  "RM.controller.CustomDiscountC": [],
  "RM.controller.CustomerInvoicesC": [],
  "RM.controller.CustomersC": [],
  "RM.controller.DashboardC": [],
  "RM.controller.EmailInvoiceC": [],
  "RM.controller.EnterPinC": [],
  "RM.controller.EnterUsernameC": [],
  "RM.controller.ExpenseDetailC": [],
  "RM.controller.ExpensesC": [],
  "RM.controller.ForgotPasswordC": [],
  "RM.controller.HistoryC": [],
  "RM.controller.InvoiceActionsC": [],
  "RM.controller.InvoiceBalanceBreakdownC": [],
  "RM.controller.InvoiceDetailC": [],
  "RM.controller.InvoiceExpenseSelectC": [],
  "RM.controller.InvoiceItemSelectC": [],
  "RM.controller.InvoiceLineItemC": [],
  "RM.controller.InvoiceTimeSelectC": [],
  "RM.controller.InvoiceTimeSelectDetailC": [],
  "RM.controller.InvoicesC": [],
  "RM.controller.ItemDetailC": [],
  "RM.controller.ItemsAmountsC": [],
  "RM.controller.ItemsC": [],
  "RM.controller.MainC": [],
  "RM.controller.ModuleSignupC": [],
  "RM.controller.ModulesC": [],
  "RM.controller.MyPreferencesC": [],
  "RM.controller.PayAmountDetailsC": [],
  "RM.controller.PayAmountInputBackC": [],
  "RM.controller.PayAmountInputC": [],
  "RM.controller.PayAmountInputNavC": [],
  "RM.controller.PayPreferencesC": [],
  "RM.controller.PayRecvCashC": [],
  "RM.controller.PayRecvChequeC": [],
  "RM.controller.PayRecvManualCardC": [],
  "RM.controller.PaySalesHistoryC": [],
  "RM.controller.PaySendReceiptC": [],
  "RM.controller.PayTransCardSignC": [],
  "RM.controller.PayTransDetailsC": [],
  "RM.controller.PayTransRefundC": [],
  "RM.controller.PayTransTerminalC": [],
  "RM.controller.PayTransTypeSelectC": [],
  "RM.controller.PinAuthenticationC": [],
  "RM.controller.ProjectsC": [],
  "RM.controller.ReceiptPhotoPreviewC": [],
  "RM.controller.SuppliersC": [],
  "RM.controller.TestScreenC": [],
  "RM.controller.TimeSheetDetailC": [],
  "RM.controller.TimeSheetsC": [],
  "RM.controller.TimeSheetsCalendarC": [],
  "RM.core.AppMgr": [],
  "RM.core.CashbookMgr": [
    "RM.CashbookMgr"
  ],
  "RM.core.Consts": [
    "RM.Consts"
  ],
  "RM.core.ContactsMgr": [
    "RM.ContactsMgr"
  ],
  "RM.core.EventMgr": [
    "RM.EventMgr"
  ],
  "RM.core.ExpensesMgr": [
    "RM.ExpensesMgr"
  ],
  "RM.core.HomeSettingsMgr": [
    "RM.HomeSettingsMgr"
  ],
  "RM.core.InvoicesMgr": [
    "RM.InvoicesMgr"
  ],
  "RM.core.PayMgr": [
    "RM.PayMgr"
  ],
  "RM.core.PermissionsMgr": [
    "RM.PermissionsMgr"
  ],
  "RM.core.PopupNrPad": [
    "RM.PopupNrPad"
  ],
  "RM.core.Selectors": [
    "RM.Selectors"
  ],
  "RM.core.SessionManager": [
    "RM.SessionManager"
  ],
  "RM.core.TimeSheetsMgr": [
    "RM.TimeSheetsMgr"
  ],
  "RM.core.ViewMgr": [
    "RM.ViewMgr"
  ],
  "RM.model.AccountingCategory": [],
  "RM.model.BankAccount": [],
  "RM.model.Bill": [],
  "RM.model.BudgetLineItem": [],
  "RM.model.CardType": [],
  "RM.model.CashBook": [],
  "RM.model.Contact": [],
  "RM.model.Customer": [],
  "RM.model.CustomerInvoice": [],
  "RM.model.Expense": [],
  "RM.model.GSTCode": [],
  "RM.model.History": [],
  "RM.model.Invoice": [],
  "RM.model.InvoiceExpenseSelect": [],
  "RM.model.InvoiceTemplate": [],
  "RM.model.InvoiceTimeSelect": [],
  "RM.model.Item": [],
  "RM.model.ItemType": [],
  "RM.model.PaymentMethod": [],
  "RM.model.Project": [],
  "RM.model.Project1": [],
  "RM.model.Supplier": [],
  "RM.model.TaxStatus": [],
  "RM.model.TimeEntry": [],
  "RM.model.TimeEntryCalendar": [],
  "RM.model.Transaction": [],
  "RM.model.TransactionHistory": [],
  "RM.model.TransactionMethod": [],
  "RM.store.AccountingCategories": [],
  "RM.store.BankAccounts": [],
  "RM.store.Bills": [],
  "RM.store.BudgetLineItems": [],
  "RM.store.CardTypes": [],
  "RM.store.CashBooks": [],
  "RM.store.Contacts": [],
  "RM.store.CustomerInvoices": [],
  "RM.store.Customers": [],
  "RM.store.Expenses": [],
  "RM.store.GSTCodes": [],
  "RM.store.Histories": [],
  "RM.store.InvoiceExpenseSelect": [],
  "RM.store.InvoiceTemplates": [],
  "RM.store.InvoiceTimeSelect": [],
  "RM.store.Invoices": [],
  "RM.store.ItemTypes": [],
  "RM.store.Items": [],
  "RM.store.PaymentMethods": [],
  "RM.store.Projects": [],
  "RM.store.RmBaseStore": [],
  "RM.store.Suppliers": [],
  "RM.store.TaxStatuses": [],
  "RM.store.TimeEntries": [],
  "RM.store.TimeEntriesCalendar": [],
  "RM.store.TransactionMethods": [],
  "RM.store.Transactions": [],
  "RM.store.TransactionsHistory": [],
  "RM.util.Dates": [],
  "RM.util.Device": [
    "RM.Device"
  ],
  "RM.util.FormUtils": [],
  "RM.util.Log": [
    "RM.Log"
  ],
  "RM.util.MathHelpers": [],
  "RM.util.PseudoGuid": [],
  "RM.view.About": [],
  "RM.view.AcceptPayment": [],
  "RM.view.AcceptPaymentMsg": [],
  "RM.view.AcceptPaymentType": [],
  "RM.view.Accounts": [],
  "RM.view.AddNote": [],
  "RM.view.AppStop": [],
  "RM.view.CashBooks": [],
  "RM.view.ContactDetail": [],
  "RM.view.Contacts": [],
  "RM.view.CreateItem": [],
  "RM.view.CreatePin": [],
  "RM.view.CustomDiscount": [],
  "RM.view.CustomerInvoices": [],
  "RM.view.CustomerSelect": [],
  "RM.view.Customers": [],
  "RM.view.EmailInvoice": [],
  "RM.view.EnterPin": [],
  "RM.view.EnterUsername": [],
  "RM.view.ExpenseDetail": [],
  "RM.view.Expenses": [],
  "RM.view.ForgotPassword": [],
  "RM.view.History": [],
  "RM.view.InvoiceActions": [],
  "RM.view.InvoiceBalanceBreakdown": [],
  "RM.view.InvoiceDetail": [],
  "RM.view.InvoiceExpenseSelect": [],
  "RM.view.InvoiceItemSelect": [],
  "RM.view.InvoiceLineItem": [],
  "RM.view.InvoiceTimeSelect": [],
  "RM.view.InvoiceTimeSelectDetail": [],
  "RM.view.Invoices": [],
  "RM.view.ItemDetail": [],
  "RM.view.Items": [],
  "RM.view.ItemsAmounts": [],
  "RM.view.Main": [],
  "RM.view.MainNavContainer": [],
  "RM.view.ModuleSignup": [],
  "RM.view.Modules": [],
  "RM.view.PayAmountDetails": [],
  "RM.view.PayAmountInput": [],
  "RM.view.PayAmountInputBack": [],
  "RM.view.PayAmountInputNav": [],
  "RM.view.PayPreferences": [],
  "RM.view.PayRecvCash": [],
  "RM.view.PayRecvCheque": [],
  "RM.view.PayRecvManualCard": [],
  "RM.view.PaySalesHistory": [],
  "RM.view.PaySendReceipt": [],
  "RM.view.PayTransCardSign": [],
  "RM.view.PayTransDetails": [],
  "RM.view.PayTransRefund": [],
  "RM.view.PayTransTerminal": [],
  "RM.view.PayTransTypeSelect": [],
  "RM.view.PinAuthentication": [],
  "RM.view.Projects": [],
  "RM.view.ReceiptPhotoPreview": [],
  "RM.view.ReceiptUpload": [],
  "RM.view.Suppliers": [],
  "RM.view.TestScreen": [],
  "RM.view.TimeSheetDetail": [],
  "RM.view.TimeSheets": [],
  "RM.view.TimeSheetsCalendar": [],
  "RM.view.bankaccounts.BankAccounts": [],
  "RM.view.bills.Bills": [],
  "RM.view.budgets.Budgets": [],
  "RM.view.budgets.LineItems": [],
  "RM.view.dashboard.Alerts": [],
  "RM.view.dashboard.BudgetOverview": [],
  "RM.view.dashboard.Dashboard": [],
  "RM.view.dashboard.NetPosition": [],
  "RM.view.dashboard.TopExpenses": [],
  "RM.view.settings.CompanySettings": [],
  "RM.view.settings.CoreSettings": [],
  "RM.view.settings.LinkBankAccount": [],
  "RM.view.settings.MyPreferences": [],
  "TouchCalendarViewModel": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.ActionSheet": [
    "widget.actionsheet"
  ],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.AnimationQueue": [],
  "Ext.Audio": [
    "widget.audio"
  ],
  "Ext.BingMap": [
    "widget.bingmap"
  ],
  "Ext.Button": [
    "widget.button"
  ],
  "Ext.Component": [
    "widget.component"
  ],
  "Ext.ComponentManager": [],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "widget.container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [],
  "Ext.Img": [
    "widget.image",
    "widget.img"
  ],
  "Ext.ItemCollection": [],
  "Ext.Label": [
    "widget.label"
  ],
  "Ext.LoadMask": [
    "widget.loadmask"
  ],
  "Ext.Map": [
    "widget.map"
  ],
  "Ext.Mask": [
    "widget.mask"
  ],
  "Ext.Media": [
    "widget.media"
  ],
  "Ext.Menu": [
    "widget.menu"
  ],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "widget.panel"
  ],
  "Ext.ProgressIndicator": [
    "widget.progressindicator"
  ],
  "Ext.Promise": [],
  "Ext.SegmentedButton": [
    "widget.segmentedbutton"
  ],
  "Ext.Sheet": [
    "widget.sheet"
  ],
  "Ext.Sortable": [],
  "Ext.Spacer": [
    "widget.spacer"
  ],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [
    "widget.title"
  ],
  "Ext.TitleBar": [
    "widget.titlebar"
  ],
  "Ext.Toolbar": [
    "widget.toolbar"
  ],
  "Ext.Video": [
    "widget.video"
  ],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "widget.carousel"
  ],
  "Ext.carousel.Indicator": [
    "widget.carouselindicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.data.ArrayStore": [
    "store.array"
  ],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [
    "store.direct"
  ],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [
    "data.field"
  ],
  "Ext.data.JsonP": [],
  "Ext.data.JsonStore": [
    "store.json"
  ],
  "Ext.data.Model": [],
  "Ext.data.ModelManager": [],
  "Ext.data.NodeInterface": [],
  "Ext.data.NodeStore": [
    "store.node"
  ],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [
    "store.store"
  ],
  "Ext.data.StoreManager": [],
  "Ext.data.TreeStore": [
    "store.tree"
  ],
  "Ext.data.Types": [],
  "Ext.data.Validations": [],
  "Ext.data.association.Association": [],
  "Ext.data.association.BelongsTo": [
    "association.belongsto"
  ],
  "Ext.data.association.HasMany": [
    "association.hasmany"
  ],
  "Ext.data.association.HasOne": [
    "association.hasone"
  ],
  "Ext.data.identifier.Sequential": [
    "data.identifier.sequential"
  ],
  "Ext.data.identifier.Simple": [
    "data.identifier.simple"
  ],
  "Ext.data.identifier.Uuid": [
    "data.identifier.uuid"
  ],
  "Ext.data.plugin.Buffered": [
    "plugin.storebuffered"
  ],
  "Ext.data.proxy.Ajax": [
    "proxy.ajax"
  ],
  "Ext.data.proxy.Client": [],
  "Ext.data.proxy.Direct": [
    "proxy.direct"
  ],
  "Ext.data.proxy.JsonP": [
    "proxy.jsonp",
    "proxy.scripttag"
  ],
  "Ext.data.proxy.LocalStorage": [
    "proxy.localstorage"
  ],
  "Ext.data.proxy.Memory": [
    "proxy.memory"
  ],
  "Ext.data.proxy.Proxy": [
    "proxy.proxy"
  ],
  "Ext.data.proxy.Rest": [
    "proxy.rest"
  ],
  "Ext.data.proxy.Server": [
    "proxy.server"
  ],
  "Ext.data.proxy.SessionStorage": [
    "proxy.sessionstorage"
  ],
  "Ext.data.proxy.Sql": [
    "proxy.sql"
  ],
  "Ext.data.proxy.WebStorage": [],
  "Ext.data.reader.Array": [
    "reader.array"
  ],
  "Ext.data.reader.Json": [
    "reader.json"
  ],
  "Ext.data.reader.Reader": [],
  "Ext.data.reader.Xml": [
    "reader.xml"
  ],
  "Ext.data.writer.Json": [
    "writer.json"
  ],
  "Ext.data.writer.Writer": [
    "writer.base"
  ],
  "Ext.data.writer.Xml": [
    "writer.xml"
  ],
  "Ext.dataview.DataView": [
    "widget.dataview"
  ],
  "Ext.dataview.IndexBar": [],
  "Ext.dataview.List": [
    "widget.list"
  ],
  "Ext.dataview.ListItemHeader": [
    "widget.listitemheader"
  ],
  "Ext.dataview.NestedList": [
    "widget.nestedlist"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [
    "widget.dataitem"
  ],
  "Ext.dataview.component.ListItem": [
    "widget.listitem"
  ],
  "Ext.dataview.component.SimpleListItem": [
    "widget.simplelistitem"
  ],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Accelerometer": [],
  "Ext.device.Browser": [],
  "Ext.device.Camera": [],
  "Ext.device.Capture": [],
  "Ext.device.Communicator": [],
  "Ext.device.Compass": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.FileSystem": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Globalization": [],
  "Ext.device.Media": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Push": [],
  "Ext.device.SQLite": [],
  "Ext.device.Splashscreen": [],
  "Ext.device.Storage": [],
  "Ext.device.Tunnel": [],
  "Ext.device.accelerometer.Abstract": [],
  "Ext.device.accelerometer.Cordova": [],
  "Ext.device.accelerometer.Simulator": [],
  "Ext.device.browser.Abstract": [],
  "Ext.device.browser.Cordova": [],
  "Ext.device.browser.Simulator": [],
  "Ext.device.browser.Window": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.Cordova": [],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.capture.Abstract": [],
  "Ext.device.capture.Cordova": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.compass.Abstract": [],
  "Ext.device.compass.Cordova": [],
  "Ext.device.compass.Simulator": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.Cordova": [],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Cordova": [],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.Cordova": [],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.filesystem.Abstract": [],
  "Ext.device.filesystem.Chrome": [],
  "Ext.device.filesystem.Cordova": [],
  "Ext.device.filesystem.DirectoryEntry": [],
  "Ext.device.filesystem.Entry": [],
  "Ext.device.filesystem.FileEntry": [],
  "Ext.device.filesystem.FileSystem": [],
  "Ext.device.filesystem.HTML5": [],
  "Ext.device.filesystem.Sencha": [],
  "Ext.device.filesystem.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Cordova": [],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.globalization.Abstract": [],
  "Ext.device.globalization.Cordova": [],
  "Ext.device.globalization.Simulator": [],
  "Ext.device.media.Abstract": [],
  "Ext.device.media.Cordova": [],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.Cordova": [],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Purchase": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Cordova": [],
  "Ext.device.push.Sencha": [],
  "Ext.device.splashscreen.Abstract": [],
  "Ext.device.splashscreen.Cordova": [],
  "Ext.device.splashscreen.Simulator": [],
  "Ext.device.sqlite.Database": [],
  "Ext.device.sqlite.SQLResultSet": [],
  "Ext.device.sqlite.SQLResultSetRowList": [],
  "Ext.device.sqlite.SQLTransaction": [],
  "Ext.device.sqlite.Sencha": [],
  "Ext.device.storage.Abstract": [],
  "Ext.device.storage.Cordova": [],
  "Ext.device.storage.HTML5.Database": [],
  "Ext.device.storage.HTML5.HTML5": [],
  "Ext.device.storage.HTML5.SQLStatement": [],
  "Ext.device.storage.Simulator": [],
  "Ext.device.tunnel.Abstract": [],
  "Ext.device.tunnel.Connection": [],
  "Ext.device.tunnel.Sencha": [],
  "Ext.device.tunnel.Simulator": [],
  "Ext.direct.Event": [
    "direct.event"
  ],
  "Ext.direct.ExceptionEvent": [
    "direct.exception"
  ],
  "Ext.direct.JsonProvider": [
    "direct.jsonprovider"
  ],
  "Ext.direct.Manager": [],
  "Ext.direct.PollingProvider": [
    "direct.pollingprovider"
  ],
  "Ext.direct.Provider": [
    "direct.provider"
  ],
  "Ext.direct.RemotingEvent": [
    "direct.rpc"
  ],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [
    "direct.remotingprovider"
  ],
  "Ext.direct.Transaction": [
    "direct.transaction"
  ],
  "Ext.dom.CompositeElement": [],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.EdgeSwipe": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "widget.checkboxfield"
  ],
  "Ext.field.DatePicker": [
    "widget.datepickerfield"
  ],
  "Ext.field.DatePickerNative": [
    "widget.datepickernativefield"
  ],
  "Ext.field.Email": [
    "widget.emailfield"
  ],
  "Ext.field.Field": [
    "widget.field"
  ],
  "Ext.field.File": [
    "widget.filefield"
  ],
  "Ext.field.FileInput": [
    "widget.fileinput"
  ],
  "Ext.field.Hidden": [
    "widget.hiddenfield"
  ],
  "Ext.field.Input": [
    "widget.input"
  ],
  "Ext.field.Number": [
    "widget.numberfield"
  ],
  "Ext.field.Password": [
    "widget.passwordfield"
  ],
  "Ext.field.Radio": [
    "widget.radiofield"
  ],
  "Ext.field.Search": [
    "widget.searchfield"
  ],
  "Ext.field.Select": [
    "widget.selectfield"
  ],
  "Ext.field.Slider": [
    "widget.sliderfield"
  ],
  "Ext.field.Spinner": [
    "widget.spinnerfield"
  ],
  "Ext.field.Text": [
    "widget.textfield"
  ],
  "Ext.field.TextArea": [
    "widget.textareafield"
  ],
  "Ext.field.TextAreaInput": [
    "widget.textareainput"
  ],
  "Ext.field.Toggle": [
    "widget.togglefield"
  ],
  "Ext.field.Url": [
    "widget.urlfield"
  ],
  "Ext.form.FieldSet": [
    "widget.fieldset"
  ],
  "Ext.form.Panel": [
    "widget.formpanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [
    "animation.cube"
  ],
  "Ext.fx.animation.Fade": [
    "animation.fade",
    "animation.fadeIn"
  ],
  "Ext.fx.animation.FadeOut": [
    "animation.fadeOut"
  ],
  "Ext.fx.animation.Flip": [
    "animation.flip"
  ],
  "Ext.fx.animation.Pop": [
    "animation.pop",
    "animation.popIn"
  ],
  "Ext.fx.animation.PopOut": [
    "animation.popOut"
  ],
  "Ext.fx.animation.Slide": [
    "animation.slide",
    "animation.slideIn"
  ],
  "Ext.fx.animation.SlideOut": [
    "animation.slideOut"
  ],
  "Ext.fx.animation.Wipe": [],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [
    "easing.ease-in"
  ],
  "Ext.fx.easing.EaseOut": [
    "easing.ease-out"
  ],
  "Ext.fx.easing.Linear": [
    "easing.linear"
  ],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [
    "fx.layout.card.cover"
  ],
  "Ext.fx.layout.card.Cube": [
    "fx.layout.card.cube"
  ],
  "Ext.fx.layout.card.Fade": [
    "fx.layout.card.fade"
  ],
  "Ext.fx.layout.card.Flip": [
    "fx.layout.card.flip"
  ],
  "Ext.fx.layout.card.Pop": [
    "fx.layout.card.pop"
  ],
  "Ext.fx.layout.card.Reveal": [
    "fx.layout.card.reveal"
  ],
  "Ext.fx.layout.card.Scroll": [
    "fx.layout.card.scroll"
  ],
  "Ext.fx.layout.card.ScrollCover": [
    "fx.layout.card.scrollcover"
  ],
  "Ext.fx.layout.card.ScrollReveal": [
    "fx.layout.card.scrollreveal"
  ],
  "Ext.fx.layout.card.Slide": [
    "fx.layout.card.slide"
  ],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [
    "layout.tablebox"
  ],
  "Ext.layout.Card": [
    "layout.card"
  ],
  "Ext.layout.Default": [
    "layout.auto",
    "layout.default"
  ],
  "Ext.layout.Fit": [
    "layout.fit"
  ],
  "Ext.layout.FlexBox": [
    "layout.box"
  ],
  "Ext.layout.Float": [
    "layout.float"
  ],
  "Ext.layout.HBox": [
    "layout.hbox"
  ],
  "Ext.layout.VBox": [
    "layout.vbox"
  ],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [],
  "Ext.mixin.Progressable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "widget.navigationview"
  ],
  "Ext.picker.Date": [
    "widget.datepicker"
  ],
  "Ext.picker.Picker": [
    "widget.picker"
  ],
  "Ext.picker.Slot": [
    "widget.pickerslot"
  ],
  "Ext.plugin.BufferedList": [
    "plugin.bufferedlist"
  ],
  "Ext.plugin.ListPaging": [
    "plugin.listpaging"
  ],
  "Ext.plugin.PullRefresh": [
    "plugin.pullrefresh"
  ],
  "Ext.plugin.SortableList": [
    "plugin.sortablelist"
  ],
  "Ext.scroll.Indicator": [],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Rounded": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.slider.Slider": [
    "widget.slider"
  ],
  "Ext.slider.Thumb": [
    "widget.thumb"
  ],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "widget.tabbar"
  ],
  "Ext.tab.Panel": [
    "widget.tabpanel"
  ],
  "Ext.tab.Tab": [
    "widget.tab"
  ],
  "Ext.table.Cell": [
    "widget.tablecell"
  ],
  "Ext.table.Row": [
    "widget.tablerow"
  ],
  "Ext.table.Table": [
    "widget.table"
  ],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Audio": [],
  "Ext.util.BufferedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.InputBlocker": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.ActionOverFlowMenuButton": [],
  "Ext.ux.ApplicationMenu": [],
  "Ext.ux.ContextMenu": [],
  "Ext.ux.MenuButton": [],
  "Ext.ux.TabMenuButton": [],
  "Ext.ux.device.Analytics": [],
  "Ext.ux.device.Twitter": [],
  "Ext.ux.device.analytics.Abstract": [],
  "Ext.ux.device.analytics.Cordova": [],
  "Ext.ux.device.twitter.Abstract": [],
  "Ext.ux.device.twitter.Cordova": [],
  "Ext.ux.parse.Helper": [],
  "Ext.ux.parse.Model": [],
  "Ext.ux.parse.Proxy": [
    "proxy.parse"
  ],
  "Ext.ux.parse.Reader": [
    "reader.parse"
  ],
  "Ext.ux.parse.Store": [],
  "Ext.ux.parse.association.Pointer": [
    "association.pointer"
  ],
  "Ext.ux.parse.association.Relation": [
    "association.relation"
  ],
  "Ext.viewport.Android": [],
  "Ext.viewport.Default": [
    "widget.viewport"
  ],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Ext.viewport.WindowsPhone": [],
  "RM.component.CalcKeypad": [
    "widget.calckeypad"
  ],
  "RM.component.ChooseInvoiceDiscount": [],
  "RM.component.ChooseInvoiceItem": [],
  "RM.component.CustInvSummaryList": [
    "widget.custinvsummarylist"
  ],
  "RM.component.DataEntryKeypad": [
    "widget.dataentrykeypad"
  ],
  "RM.component.DropdownButton": [
    "widget.dropdownbutton"
  ],
  "RM.component.DropdownMenu": [
    "widget.dropdownmenu"
  ],
  "RM.component.DropdownOverlay": [
    "widget.dropdownoverlay"
  ],
  "RM.component.DurationField": [
    "widget.durationfield"
  ],
  "RM.component.DurationPicker": [
    "widget.durationpicker"
  ],
  "RM.component.ExtDatePickerField": [
    "widget.extdatepickerfield"
  ],
  "RM.component.ExtEmailField": [
    "widget.extemailfield"
  ],
  "RM.component.ExtNumberField": [
    "widget.extnumberfield"
  ],
  "RM.component.ExtSelectField": [
    "widget.extselectfield"
  ],
  "RM.component.ExtTextField": [
    "widget.exttextfield"
  ],
  "RM.component.InvoiceLineItems": [
    "widget.invoicelineitems"
  ],
  "RM.component.InvoiceTimeSelectDetailPan": [
    "widget.invoicetimeselectdetailpan"
  ],
  "RM.component.InvoicesList": [
    "widget.invoiceslist"
  ],
  "RM.component.PayAmountInputCalc": [
    "widget.payamountinputcalc"
  ],
  "RM.component.PinKeypad": [
    "widget.pinkeypad"
  ],
  "RM.component.PinOptions": [],
  "RM.component.Popup": [],
  "RM.component.PopupNotes": [],
  "RM.component.RMAmountField": [
    "widget.rmamountfield"
  ],
  "RM.component.RMAmountFieldKeyPad": [
    "widget.rmamountfieldkeypad"
  ],
  "RM.component.RMCanvas": [
    "widget.rmcanvas"
  ],
  "RM.component.RMCheckbox": [
    "widget.rmcheckbox"
  ],
  "RM.component.RMComponent": [],
  "RM.component.RMList": [
    "widget.rmlist"
  ],
  "RM.component.RMMsgPopup": [],
  "RM.component.RMNumberField": [
    "widget.rmnumberfield"
  ],
  "RM.component.RMPhoneField": [
    "widget.rmphonefield"
  ],
  "RM.component.RMPicker": [],
  "RM.component.RMPullRefresh": [
    "rmpullrefresh"
  ],
  "RM.component.RMSelectScreenField": [
    "widget.rmselectscreenfield"
  ],
  "RM.component.RMToggleField": [
    "widget.rmtogglefield"
  ],
  "RM.component.SecureButton": [
    "widget.securebutton"
  ],
  "RM.component.SecureFormPanel": [
    "widget.secureformpanel"
  ],
  "RM.component.SecurePanel": [
    "widget.securepanel"
  ],
  "RM.component.SortSearchBar": [
    "widget.sortsearchbar"
  ],
  "RM.component.VisibleOnFocus": [],
  "RM.component.slidenavigation.View": [
    "widget.slidenavigationview"
  ],
  "RM.component.touchcalendar.TouchCalendarSimpleEvents": [],
  "RM.component.touchcalendar.TouchCalendarView": [],
  "RM.controller.AboutC": [],
  "RM.controller.AcceptPaymentC": [],
  "RM.controller.AccountsC": [],
  "RM.controller.AddNoteC": [],
  "RM.controller.AppStopC": [],
  "RM.controller.BillsC": [],
  "RM.controller.BudgetLineItemsC": [],
  "RM.controller.CashBooksC": [],
  "RM.controller.ContactDetailC": [],
  "RM.controller.ContactsC": [],
  "RM.controller.CoreSettingsC": [],
  "RM.controller.CreateItemC": [],
  "RM.controller.CreatePinC": [],
  "RM.controller.CustomDiscountC": [],
  "RM.controller.CustomerInvoicesC": [],
  "RM.controller.CustomersC": [],
  "RM.controller.DashboardC": [],
  "RM.controller.EmailInvoiceC": [],
  "RM.controller.EnterPinC": [],
  "RM.controller.EnterUsernameC": [],
  "RM.controller.ExpenseDetailC": [],
  "RM.controller.ExpensesC": [],
  "RM.controller.ForgotPasswordC": [],
  "RM.controller.HistoryC": [],
  "RM.controller.InvoiceActionsC": [],
  "RM.controller.InvoiceBalanceBreakdownC": [],
  "RM.controller.InvoiceDetailC": [],
  "RM.controller.InvoiceExpenseSelectC": [],
  "RM.controller.InvoiceItemSelectC": [],
  "RM.controller.InvoiceLineItemC": [],
  "RM.controller.InvoiceTimeSelectC": [],
  "RM.controller.InvoiceTimeSelectDetailC": [],
  "RM.controller.InvoicesC": [],
  "RM.controller.ItemDetailC": [],
  "RM.controller.ItemsAmountsC": [],
  "RM.controller.ItemsC": [],
  "RM.controller.MainC": [],
  "RM.controller.ModuleSignupC": [],
  "RM.controller.ModulesC": [],
  "RM.controller.MyPreferencesC": [],
  "RM.controller.PayAmountDetailsC": [],
  "RM.controller.PayAmountInputBackC": [],
  "RM.controller.PayAmountInputC": [],
  "RM.controller.PayAmountInputNavC": [],
  "RM.controller.PayPreferencesC": [],
  "RM.controller.PayRecvCashC": [],
  "RM.controller.PayRecvChequeC": [],
  "RM.controller.PayRecvManualCardC": [],
  "RM.controller.PaySalesHistoryC": [],
  "RM.controller.PaySendReceiptC": [],
  "RM.controller.PayTransCardSignC": [],
  "RM.controller.PayTransDetailsC": [],
  "RM.controller.PayTransRefundC": [],
  "RM.controller.PayTransTerminalC": [],
  "RM.controller.PayTransTypeSelectC": [],
  "RM.controller.PinAuthenticationC": [],
  "RM.controller.ProjectsC": [],
  "RM.controller.ReceiptPhotoPreviewC": [],
  "RM.controller.SuppliersC": [],
  "RM.controller.TestScreenC": [],
  "RM.controller.TimeSheetDetailC": [],
  "RM.controller.TimeSheetsC": [],
  "RM.controller.TimeSheetsCalendarC": [],
  "RM.core.AppMgr": [],
  "RM.core.CashbookMgr": [],
  "RM.core.Consts": [],
  "RM.core.ContactsMgr": [],
  "RM.core.EventMgr": [],
  "RM.core.ExpensesMgr": [],
  "RM.core.HomeSettingsMgr": [],
  "RM.core.InvoicesMgr": [],
  "RM.core.PayMgr": [],
  "RM.core.PermissionsMgr": [],
  "RM.core.PopupNrPad": [],
  "RM.core.Selectors": [],
  "RM.core.SessionManager": [],
  "RM.core.TimeSheetsMgr": [],
  "RM.core.ViewMgr": [],
  "RM.model.AccountingCategory": [],
  "RM.model.BankAccount": [],
  "RM.model.Bill": [],
  "RM.model.BudgetLineItem": [],
  "RM.model.CardType": [],
  "RM.model.CashBook": [],
  "RM.model.Contact": [],
  "RM.model.Customer": [],
  "RM.model.CustomerInvoice": [],
  "RM.model.Expense": [],
  "RM.model.GSTCode": [],
  "RM.model.History": [],
  "RM.model.Invoice": [],
  "RM.model.InvoiceExpenseSelect": [],
  "RM.model.InvoiceTemplate": [],
  "RM.model.InvoiceTimeSelect": [],
  "RM.model.Item": [],
  "RM.model.ItemType": [],
  "RM.model.PaymentMethod": [],
  "RM.model.Project": [],
  "RM.model.Project1": [],
  "RM.model.Supplier": [],
  "RM.model.TaxStatus": [],
  "RM.model.TimeEntry": [],
  "RM.model.TimeEntryCalendar": [],
  "RM.model.Transaction": [],
  "RM.model.TransactionHistory": [],
  "RM.model.TransactionMethod": [],
  "RM.store.AccountingCategories": [],
  "RM.store.BankAccounts": [],
  "RM.store.Bills": [],
  "RM.store.BudgetLineItems": [],
  "RM.store.CardTypes": [],
  "RM.store.CashBooks": [],
  "RM.store.Contacts": [],
  "RM.store.CustomerInvoices": [],
  "RM.store.Customers": [],
  "RM.store.Expenses": [],
  "RM.store.GSTCodes": [],
  "RM.store.Histories": [],
  "RM.store.InvoiceExpenseSelect": [],
  "RM.store.InvoiceTemplates": [],
  "RM.store.InvoiceTimeSelect": [],
  "RM.store.Invoices": [],
  "RM.store.ItemTypes": [],
  "RM.store.Items": [],
  "RM.store.PaymentMethods": [],
  "RM.store.Projects": [],
  "RM.store.RmBaseStore": [],
  "RM.store.Suppliers": [],
  "RM.store.TaxStatuses": [],
  "RM.store.TimeEntries": [],
  "RM.store.TimeEntriesCalendar": [],
  "RM.store.TransactionMethods": [],
  "RM.store.Transactions": [],
  "RM.store.TransactionsHistory": [],
  "RM.util.Dates": [],
  "RM.util.Device": [],
  "RM.util.FormUtils": [],
  "RM.util.Log": [],
  "RM.util.MathHelpers": [],
  "RM.util.PseudoGuid": [],
  "RM.view.About": [
    "widget.about"
  ],
  "RM.view.AcceptPayment": [
    "widget.acceptpayment"
  ],
  "RM.view.AcceptPaymentMsg": [
    "widget.acceptpaymentmsg"
  ],
  "RM.view.AcceptPaymentType": [
    "widget.acceptpaymenttype"
  ],
  "RM.view.Accounts": [
    "widget.accounts"
  ],
  "RM.view.AddNote": [
    "widget.addnote"
  ],
  "RM.view.AppStop": [
    "widget.appstop"
  ],
  "RM.view.CashBooks": [
    "widget.cashbooks"
  ],
  "RM.view.ContactDetail": [
    "widget.contactdetail"
  ],
  "RM.view.Contacts": [
    "widget.contacts"
  ],
  "RM.view.CreateItem": [
    "widget.createitem"
  ],
  "RM.view.CreatePin": [
    "widget.createpin"
  ],
  "RM.view.CustomDiscount": [
    "widget.customdiscount"
  ],
  "RM.view.CustomerInvoices": [
    "widget.customerinvoices"
  ],
  "RM.view.CustomerSelect": [
    "widget.customerselect"
  ],
  "RM.view.Customers": [
    "widget.customers"
  ],
  "RM.view.EmailInvoice": [
    "widget.emailinvoice"
  ],
  "RM.view.EnterPin": [
    "widget.enterpin"
  ],
  "RM.view.EnterUsername": [
    "widget.enterusername"
  ],
  "RM.view.ExpenseDetail": [
    "widget.expensedetail"
  ],
  "RM.view.Expenses": [
    "widget.expenses"
  ],
  "RM.view.ForgotPassword": [
    "widget.forgotpassword"
  ],
  "RM.view.History": [
    "widget.history"
  ],
  "RM.view.InvoiceActions": [
    "widget.invoiceactions"
  ],
  "RM.view.InvoiceBalanceBreakdown": [
    "widget.invoicebalancebreakdown"
  ],
  "RM.view.InvoiceDetail": [
    "widget.invoicedetail"
  ],
  "RM.view.InvoiceExpenseSelect": [
    "widget.invoiceexpenseselect"
  ],
  "RM.view.InvoiceItemSelect": [
    "widget.invoiceitemselect"
  ],
  "RM.view.InvoiceLineItem": [
    "widget.invoicelineitem"
  ],
  "RM.view.InvoiceTimeSelect": [
    "widget.invoicetimeselect"
  ],
  "RM.view.InvoiceTimeSelectDetail": [
    "widget.invoicetimeselectdetail"
  ],
  "RM.view.Invoices": [
    "widget.invoices"
  ],
  "RM.view.ItemDetail": [
    "widget.itemdetail"
  ],
  "RM.view.Items": [
    "widget.items"
  ],
  "RM.view.ItemsAmounts": [
    "widget.itemsamounts"
  ],
  "RM.view.Main": [
    "widget.mainview"
  ],
  "RM.view.MainNavContainer": [],
  "RM.view.ModuleSignup": [
    "widget.modulesignup"
  ],
  "RM.view.Modules": [
    "widget.modules"
  ],
  "RM.view.PayAmountDetails": [
    "widget.payamountdetails"
  ],
  "RM.view.PayAmountInput": [
    "widget.payamountinput"
  ],
  "RM.view.PayAmountInputBack": [
    "widget.payamountinputback"
  ],
  "RM.view.PayAmountInputNav": [
    "widget.payamountinputnav"
  ],
  "RM.view.PayPreferences": [
    "widget.paypreferences"
  ],
  "RM.view.PayRecvCash": [
    "widget.payrecvcash"
  ],
  "RM.view.PayRecvCheque": [
    "widget.payrecvcheque"
  ],
  "RM.view.PayRecvManualCard": [
    "widget.payrecvmanualcard"
  ],
  "RM.view.PaySalesHistory": [
    "widget.paysaleshistory"
  ],
  "RM.view.PaySendReceipt": [
    "widget.paysendreceipt"
  ],
  "RM.view.PayTransCardSign": [
    "widget.paytranscardsign"
  ],
  "RM.view.PayTransDetails": [
    "widget.paytransdetails"
  ],
  "RM.view.PayTransRefund": [
    "widget.paytransrefund"
  ],
  "RM.view.PayTransTerminal": [
    "widget.paytransterminal"
  ],
  "RM.view.PayTransTypeSelect": [
    "widget.paytranstypeselect"
  ],
  "RM.view.PinAuthentication": [
    "widget.pinauthentication"
  ],
  "RM.view.Projects": [
    "widget.projects"
  ],
  "RM.view.ReceiptPhotoPreview": [
    "widget.receiptphotopreview"
  ],
  "RM.view.ReceiptUpload": [
    "widget.receiptupload"
  ],
  "RM.view.Suppliers": [
    "widget.suppliers"
  ],
  "RM.view.TestScreen": [
    "widget.testscreen"
  ],
  "RM.view.TimeSheetDetail": [
    "widget.timesheetdetail"
  ],
  "RM.view.TimeSheets": [
    "widget.timesheets"
  ],
  "RM.view.TimeSheetsCalendar": [
    "widget.timesheetscalendar"
  ],
  "RM.view.bankaccounts.BankAccounts": [
    "widget.bankaccounts"
  ],
  "RM.view.bills.Bills": [
    "widget.bills"
  ],
  "RM.view.budgets.Budgets": [
    "widget.budgets"
  ],
  "RM.view.budgets.LineItems": [
    "widget.budgetlineitems"
  ],
  "RM.view.dashboard.Alerts": [
    "widget.dbalerts"
  ],
  "RM.view.dashboard.BudgetOverview": [
    "widget.dbbudgetoverview"
  ],
  "RM.view.dashboard.Dashboard": [
    "widget.dashboard"
  ],
  "RM.view.dashboard.NetPosition": [
    "widget.dbnetposition"
  ],
  "RM.view.dashboard.TopExpenses": [
    "widget.dbtopexpenses"
  ],
  "RM.view.settings.CompanySettings": [
    "widget.companysettings"
  ],
  "RM.view.settings.CoreSettings": [
    "widget.coresettings"
  ],
  "RM.view.settings.LinkBankAccount": [
    "widget.linkbankaccount"
  ],
  "RM.view.settings.MyPreferences": [
    "widget.mypreferences"
  ],
  "TouchCalendarViewModel": []
});
